//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universite_ASP.NET_Bootstrap_Projesi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Universite_FakulteBolumleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Universite_FakulteBolumleri()
        {
            this.Universite_Dersler = new HashSet<Universite_Dersler>();
            this.Universite_Ogrenciler = new HashSet<Universite_Ogrenciler>();
            this.Universite_OgretimGorevlileri = new HashSet<Universite_OgretimGorevlileri>();
            this.Universite_Projeler = new HashSet<Universite_Projeler>();
        }
    
        public int FakulteBolumNo { get; set; }
        [DisplayName("Bölüm Baþkaný")]
        public string FakulteBolumBaskani { get; set; }
        [DisplayName("Bölüm Baþarý Puanlamasý")]
        public int FakulteBolumBasariPuanlamasi { get; set; }
        [DisplayName("Öðrenci Sayýsý")]
        public int OgrenciSayisi { get; set; }
        [DisplayName("Öðretim Görevlisi Sayýsý")]
        public int OgretimGorevlisiSayisi { get; set; }
        public string TelefonNo { get; set; }
        public Nullable<int> OgrenciNo { get; set; }
        public Nullable<int> ProjeNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Universite_Dersler> Universite_Dersler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Universite_Ogrenciler> Universite_Ogrenciler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Universite_OgretimGorevlileri> Universite_OgretimGorevlileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Universite_Projeler> Universite_Projeler { get; set; }
    }
}
