//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universite_ASP.NET_Bootstrap_Projesi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Universite_OgretimGorevlileri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Universite_OgretimGorevlileri()
        {
            this.Universite_Dersler = new HashSet<Universite_Dersler>();
            this.Universite_Projeler = new HashSet<Universite_Projeler>();
        }
    
        public int OgretimGorevlisiNo { get; set; }
        [DisplayName("Ad Soyad")]
        public string OgretimGorevlisiAdiSoyadi { get; set; }
        [DisplayName("Mezuniyeti")]
        public string OgretimGorevlisiOkul { get; set; }
        [DisplayName("Ders")]
        public string OgretimGorevlisiDers { get; set; }
        [DisplayName("Proje")]
        public string OgretimGorevlisiProje { get; set; }
        public string TelefonNo { get; set; }
        public Nullable<int> FakulteBolumNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Universite_Dersler> Universite_Dersler { get; set; }
        public virtual Universite_FakulteBolumleri Universite_FakulteBolumleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Universite_Projeler> Universite_Projeler { get; set; }
    }
}
