//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universite_ASP.NET_Bootstrap_Projesi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Universite_MVCASPNET_ProjesiEntities : DbContext
    {
        public Universite_MVCASPNET_ProjesiEntities()
            : base("name=Universite_MVCASPNET_ProjesiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Universite_Dersler> Universite_Dersler { get; set; }
        public virtual DbSet<Universite_FakulteBolumleri> Universite_FakulteBolumleri { get; set; }
        public virtual DbSet<Universite_Ogrenciler> Universite_Ogrenciler { get; set; }
        public virtual DbSet<Universite_OgretimGorevlileri> Universite_OgretimGorevlileri { get; set; }
        public virtual DbSet<Universite_Projeler> Universite_Projeler { get; set; }
        public virtual DbSet<Universite_Users> Universite_Users { get; set; }
    }
}
