//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universite_ASP.NET_Bootstrap_Projesi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Universite_Ogrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Universite_Ogrenciler()
        {
            this.Universite_Dersler = new HashSet<Universite_Dersler>();
        }
    
        public int OgrenciNo { get; set; }
        [DisplayName("Ad Soyad")]
        public string OgrenciAdSoyad { get; set; }
        [DisplayName("Puanlama")]
        public int OgrenciPuanlama { get; set; }
        [DisplayName("Yaþ")]
        public int Yas { get; set; }
        public string Adres { get; set; }
        public Nullable<decimal> Odeme { get; set; }
        public Nullable<int> ProjeNo { get; set; }
        public Nullable<int> FakulteBolumNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Universite_Dersler> Universite_Dersler { get; set; }
        public virtual Universite_FakulteBolumleri Universite_FakulteBolumleri { get; set; }
        public virtual Universite_Projeler Universite_Projeler { get; set; }
    }
}
